### PR TITLE
add SQL scripts with python script to generate them

### PR DESCRIPTION
**Pull request by mdahlman**
Closes issue #42 

I believe the file `names-mysql.sql` is obsoleted by this update, and it should be removed. But I did not touch it as part of this commit.

### CODE REVIEW

**Comment by NickCrews** [comment]
FYI @mdahlman you can check the formatting locally by

cd python
pip install hatch
hatch run lint

or 

hatch run CMD

eg

hatch run isort .

**Comment by mdahlman** [comment]
Thanks!
I figured such a thing was of course possible. But I wasn't sure how to do it.
My clunky fix process eventually got there. But I'll test locally in the future.

**Comment by mdahlman** [comment]
But... I'm not sure what I would need to do regarding this final PyPI error.

**Comment by NickCrews** [comment]
Couple thoughts

- At this point with 3 sql files, I think they should go in their own sql/ folder
- We need a CI check similar to the normalize check to ensure that the .sql files are up to date
- Where you put the python script currently includes it in the python distribution, which we don't want. Can you put it in /sql along with the rest?
- The header of names.sql looks malformed, the CREATE TABLE statement is part of a comment

You want to adjust any of those? I can clean up later too if any of that seems more than you bargained for, this is a great start!

**Comment by mdahlman** [comment]
Yes, I see what you mean. I made these changes:
- moved all 4 files into `./sql`
- fixed the creation line that sneaked into the comment as I reformatted

Regarding the CI check: the idea is clear. But I'm not sure about the details. I suppose that `generate_sql.py` would need to be more configurable to accept output filenames. I could make that parallel to `normalize.py`. I see that a section would be needed in `ci.yml`. I don't know how to test an action like that, so it might not be practical for me to add that. Is there any simple way to test that?

**Comment by NickCrews** [comment]
@mdahlman Those fixes look awesome. I'll merge this (in case you want it ASAP) and add the CI check when I get the chance. Thanks!

**Pull request merged**
